# Generated by Django 4.0.3 on 2022-04-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_chatmessage_message_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message_to',
            new_name='receiver',
        ),
    ]
